Making rust_std attr in rust_toolchain mandatory (#1984)
`rust_toolchain`'s `rust_std` attribute should be mandatory because when it's empty, [this line](https://github.com/bazelbuild/rules_rust/blob/56e7604879ac74cb8c3d65cbb5d41611f7424977/rust/toolchain.bzl#L147) will always fail with

```
if not rust_common.stdlib_info in rust_std:
Error: unsupported binary operation: Provider in NoneType
```